[package]
name = "thermopro"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.6"
futures = "0.3.31"
pretty_env_logger = "0.5.0"
tokio = { version = "1.42.0", features = ["full"] }
uuid = { version = "1.11.1", features = ["v4"] }
